# Generated by Django 5.2.17 on 2026-09-01 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0004_certification_language_organization_education_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tiktok',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile/gallery/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='portofolio.profile')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
